# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "2303050115" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/workshop/2303050115/items/{ItemId}.png" # The repository of the override.