# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "2822806430" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/workshop/2822806430/items/{ItemId}.png" # The repository of the override.