# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "3742854577" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/workshop/3742854577/items/{ItemId}.png" # The repository of the override.