# Use this in your UnturnedImages/config.yaml file
- WorkshopId: "1959614756" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/F-Plugins/UnturnedImages@images/workshop/1959614756/items/{ItemId}.png" # The repository of the override.